
import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../components/Navbar';
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '../components/Footer'


const Home = () => {
  return (
    <div>
      <Head>
        <title>EtherRush</title>
        <meta
          content="Generated by EtherRush"
          name="Ethereum based Game"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <Nav />
        
        {/* Add your content here */}
        <div style={{ textAlign: 'center' }}>
        <Image
          src="/cowboyplayingcard.png"
          width={1000}
          height={1000}
          alt="Cowboy"
        />
      </div>
      <Footer />
      </main>
    </div>
  );
};

export default Home;
